#!/bin/bash

cp ~/.bashrc .
cp ~/.bash_aliases .
cp ~/Installs/scripts/* .
find -E ~/.config/nvim -type file -not -regex '.*(.git/|.DS_Store).*' -print \
| while read -r file; do \
    relative="${file#/Users/avrittrohwer/.config/}"; \
    dir="${relative%/*}"; \
    [ -d "$dir" ] || mkdir -p ./"$dir"; \
    cp "$file" ./"$relative"; \
done
