#!/bin/bash

cp ./.bashrc ~/.bashrc
cp ./.bash_aliases ~/.bash_aliases

if [ ! -d ~/Installs ]; then
    mkdir ~/Installs
fi
cp ./condense-path ~/Installs

if [ ! -d ~/.config/nvim ]; then
    mkdir ~/.config/nvim
fi
cp -r nvim ~/.config
