#!/bin/bash

FIFO="/tmp/dvtm-custom.$$"

[ -p "FIFO" ] || mkfifo -m 600 "$FIFO" || exit 1

while true; do
    date '+%a %F %R' # e.g. Wed 2020-04-01 13:55
    sleep 20
done > "$FIFO" &

STATUS_PID=$!
dvtm -M -m ^a -d 0 -s "$FIFO" -h 100000 3> /dev/null
kill $STATUS_PID
wait $STATUS_PID 2> /dev/null
rm -f "$FIFO"
